import { useRouter } from "next/router";
import React, { useEffect } from "react";
import DividerText from "../../components/DividerText/DividerText";
import MainLayout from "../../Layouts/MainLayout";
import Head from "next/head";
import { Container } from "@mui/material";
import OfferCard from "../../components/OfferCard/OfferCard";
export async function getStaticPaths() {
  return {
    paths: [{ params: { category: "نظارات" } }],
    fallback: true,
  };
}

export async function getStaticProps({ params }) {
  return { props: { test: "props" } };
}
function Category() {
  const router = useRouter();
  const { category } = router.query;

  return (
    <>
      <Head>
        <title>E-commerce - {category}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="favourits">
        <div className="grey-bg" style={{ minHeight: "80vh" }}>
          <Container maxWidth="lg">
            <DividerText title={category} />
            <div className="favourits-row">
              <OfferCard name="نظارات" imgNum={1} />
              <OfferCard name="نظارات" imgNum={1} />
              <OfferCard name="نظارات" imgNum={1} />
              <OfferCard name="نظارات" imgNum={1} />
            </div>
          </Container>

          <style jsx>
            {`
              .favourits-row {
                padding: 2rem 0;
                display: flex;
                justify-content: space-between;
                flex-wrap: wrap;
              }
            `}
          </style>
        </div>
      </div>
    </>
  );
}
Category.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>;
};
export default Category;
